// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using f7Race_API.Data;

#nullable disable

namespace f7Race_API.Migrations
{
    [DbContext(typeof(F7Db))]
    [Migration("20240711213959_SixMigration")]
    partial class SixMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("f7Race_API.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalChampions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPodiums")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("f7Race_API.Models.DTOS.TrophyCountDto", b =>
                {
                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("FlagRace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("TrophyCountDto");
                });

            modelBuilder.Entity("f7Race_API.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaceId"));

                    b.Property<string>("FlagRace")
                        .HasColumnType("text");

                    b.Property<string>("ImageCircuit")
                        .HasColumnType("text");

                    b.Property<int>("Laps")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RaceId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("f7Race_API.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonId"));

                    b.Property<int>("Edition")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondId")
                        .HasColumnType("integer");

                    b.Property<int?>("ThirdId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer");

                    b.HasKey("SeasonId");

                    b.HasIndex("SecondId");

                    b.HasIndex("ThirdId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("f7Race_API.Models.SeasonBrand", b =>
                {
                    b.Property<int>("SeasonBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonBrandId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("SeasonBrandId");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonBrands");
                });

            modelBuilder.Entity("f7Race_API.Models.SeasonRace", b =>
                {
                    b.Property<int>("SeasonRaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonRaceId"));

                    b.Property<int>("EighthPosition")
                        .HasColumnType("integer");

                    b.Property<int>("FifthPosition")
                        .HasColumnType("integer");

                    b.Property<int>("FirstPosition")
                        .HasColumnType("integer");

                    b.Property<string>("FlagRace")
                        .HasColumnType("text");

                    b.Property<int>("FourthPosition")
                        .HasColumnType("integer");

                    b.Property<string>("ImageCircuit")
                        .HasColumnType("text");

                    b.Property<int>("Laps")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NinthPosition")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("SecondPosition")
                        .HasColumnType("integer");

                    b.Property<int>("SeventhPosition")
                        .HasColumnType("integer");

                    b.Property<int>("SixthPosition")
                        .HasColumnType("integer");

                    b.Property<int>("TenthPosition")
                        .HasColumnType("integer");

                    b.Property<int>("ThirdPosition")
                        .HasColumnType("integer");

                    b.HasKey("SeasonRaceId");

                    b.HasIndex("SeasonId");

                    b.ToTable("SeasonRaces");
                });

            modelBuilder.Entity("f7Race_API.Models.Trophy", b =>
                {
                    b.Property<int>("TrophyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrophyId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.HasKey("TrophyId");

                    b.HasIndex("BrandId");

                    b.HasIndex("RaceId");

                    b.ToTable("Trophies");
                });

            modelBuilder.Entity("f7Race_API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("f7Race_API.Models.Season", b =>
                {
                    b.HasOne("f7Race_API.Models.Brand", "Second")
                        .WithMany()
                        .HasForeignKey("SecondId");

                    b.HasOne("f7Race_API.Models.Brand", "Third")
                        .WithMany()
                        .HasForeignKey("ThirdId");

                    b.HasOne("f7Race_API.Models.Brand", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Second");

                    b.Navigation("Third");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("f7Race_API.Models.SeasonBrand", b =>
                {
                    b.HasOne("f7Race_API.Models.Season", null)
                        .WithMany("Brands")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("f7Race_API.Models.SeasonRace", b =>
                {
                    b.HasOne("f7Race_API.Models.Season", null)
                        .WithMany("Races")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("f7Race_API.Models.Trophy", b =>
                {
                    b.HasOne("f7Race_API.Models.Brand", "Brand")
                        .WithMany("Trophies")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("f7Race_API.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("f7Race_API.Models.Brand", b =>
                {
                    b.Navigation("Trophies");
                });

            modelBuilder.Entity("f7Race_API.Models.Season", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("Races");
                });
#pragma warning restore 612, 618
        }
    }
}
